#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/

int isBTN1()
{
    bsp_io_level_t lev1;
    R_IOPORT_PinRead(&g_ioport_ctrl, switch1, &lev1);

    return lev1;
}

int isBTN2()
{
    bsp_io_level_t lev2;
    R_IOPORT_PinRead(&g_ioport_ctrl, switch2, &lev2);

    return lev2;
}

void hal_entry(void)
{
    /* TODO: add your own code here */
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 0);
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 0);
    R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);

    while(1)
    {
        if (isBTN1() == 0)
        {
            R_BSP_SoftwareDelay (60, BSP_DELAY_UNITS_MILLISECONDS);
            if (isBTN1() == 0)
            {
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 1);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 1);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 0);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 0);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 1);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN1, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_RED2, 1);
                R_IOPORT_PinWrite(&g_ioport_ctrl, LED_GRN2, 1);
                R_BSP_SoftwareDelay (500, BSP_DELAY_UNITS_MILLISECONDS);
            }
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {

    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

